# Generated by Django 2.0.7 on 2018-07-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='truck_banners')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
